- params:
    git:
      branches:
        - main
      repoName: "frogbot-monorepo-demo-v2"
    scan:
      skipAutoFix: true
      projects:
        - workingDirs:
            - frontend
        - workingDirs:
            - backend
          pipRequirementsFile: requirements.txt
